apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: notification-app
    name: notification-app
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: notification-app
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: notification-app
        spec:
            containers:
                - image: gcr.io/slippy-gets-treats/github.com/guckin/notification-app
                  imagePullPolicy: IfNotPresent
                  name: notification-app-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    labels:
        app: notification-app
    name: notification-app-hpa-piwj
    namespace: default
spec:
    maxReplicas: 5
    metrics:
        - resource:
              name: cpu
              targetAverageUtilization: 80
          type: Resource
    minReplicas: 1
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: notification-app
---
apiVersion: v1
kind: Service
metadata:
    finalizers:
        - service.kubernetes.io/load-balancer-cleanup
    labels:
        app: notification-app
    name: notification-app-service
    namespace: default
spec:
    clusterIP: 10.0.10.139
    externalTrafficPolicy: Cluster
    ports:
        - nodePort: 30104
          port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: notification-app
    sessionAffinity: None
    type: LoadBalancer
